### ISSUE TITLE
Raspberry Pi Pico W Support?

### ISSUE THREAD

**Issue by mrzeable** [ckcr4lyf/EvilAppleJuice-ESP32#31] opened 2024-02-17 01:08 UTC
Hello all, I use this with an ESP-32, but I have a friend that has a whole bunch of Raspberry Pi Pico W's. It would be much appreciated if someone was able to port this project and make it work with the Pi Pico W.

**Comment by ckcr4lyf** [comment] 2024-02-17 04:29
Dupe of #4, sorry I am not interested in it. 

@RapierXbox had added something in an MR, maybe you can use that to do something: https://github.com/ckcr4lyf/EvilAppleJuice-ESP32/pull/28/commits/72a769b587268a38be28bfc30c11c13afa21d6dd

**Closed by ckcr4lyf** 2024-02-17 04:29 UTC
